steps:
# Build and push the image using a single step with proper authentication
- name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
  entrypoint: 'bash'
  secretEnv: ['HF_TOKEN']
  args:
    - -c
    - |
      # Install Docker
      curl -fsSL https://get.docker.com -o get-docker.sh
      sh get-docker.sh

      # Configure Docker auth for Artifact Registry
      gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # Build and push the image
      docker build \
        --secret id=HF_TOKEN \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        --build-arg torch_cuda_arch_list="" \
        --tag=${_IMAGE} \
        .

      # Push the image
      docker push ${_IMAGE}

availableSecrets:
  secretManager:
  - versionName: 'projects/${PROJECT_ID}/secrets/HF_TOKEN/versions/latest'
    env: 'HF_TOKEN'

images: ["${_IMAGE}"]
substitutions:
  _IMAGE: 'us-central1-docker.pkg.dev/${PROJECT_ID}/vllm-gemma-3-1b-it-repo/vllm-gemma-3-1b-it'


options:
  dynamicSubstitutions: true
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
