steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  entrypoint: 'bash'
  secretEnv: ['HF_TOKEN']
  args:
    - -c
    - |
      # Authenticate Docker with Artifact Registry for pushing and caching.
      gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # Make the secret available as a file for the buildx --secret flag.
      echo -n "$$HF_TOKEN" > /workspace/hf_token_secret

      # Build and push the image using buildx for secret and cache handling.
      docker buildx build \
        --tag=${_IMAGE} \
        --secret id=HF_TOKEN,src=/workspace/hf_token_secret \
        --cache-from=type=registry,ref=${_IMAGE}:latest,ignore-error=true \
        --cache-to=type=registry,ref=${_IMAGE}:cache,mode=max \
        --push \
        .

availableSecrets:
  secretManager:
  - versionName: 'projects/${PROJECT_ID}/secrets/HF_TOKEN/versions/latest'
    env: 'HF_TOKEN'

images: ["${_IMAGE}"]

substitutions:
  _IMAGE: 'us-central1-docker.pkg.dev/${PROJECT_ID}/vllm-gemma-3-1b-it-repo/vllm-gemma-3-1b-it'

options:
  dynamicSubstitutions: true
 ## machineType: "E2_HIGHCPU_32"
  machineType: "E2_HIGHCPU_16"
  logging: CLOUD_LOGGING_ONLY