steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  entrypoint: 'bash'
  secretEnv: ['HF_TOKEN']
  args: 
    - -c
    - |
        docker buildx build --tag=${_IMAGE} --secret id=HF_TOKEN,env=HF_TOKEN .


availableSecrets:
  secretManager:
  - versionName: 'projects/${PROJECT_ID}/secrets/HF_TOKEN/versions/latest'
    env: 'HF_TOKEN'

images: ["${_IMAGE}"]

substitutions:  

  _IMAGE: 'us-central1-docker.pkg.dev/${PROJECT_ID}/vllm-gemma-3-1b-it-repo/vllm-gemma-3-1b-it'


options:
  dynamicSubstitutions: true
  machineType: "E2_HIGHCPU_32"
  logging: CLOUD_LOGGING_ONLY
 