steps:
# Authenticate Docker with Artifact Registry.
- name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
  entrypoint: 'gcloud'
  args: ['auth', 'configure-docker', 'us-central1-docker.pkg.dev', '--quiet']

# Build the image using docker buildx
- name: 'gcr.io/cloud-builders/docker'
  id: build
  entrypoint: 'bash'
  secretEnv: ['HF_TOKEN']
  args:
    - -c
    - |
      docker buildx create --use --name mybuilder --driver docker-container
      docker buildx build \
        --tag=${_IMAGE} \
        --secret id=HF_TOKEN \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        --cache-from=type=registry,ref=${_IMAGE}:cache,ignore-error=true \
        --cache-to=type=registry,ref=${_IMAGE}:cache,mode=max \
        --push \
        .

availableSecrets:
  secretManager:
  - versionName: 'projects/${PROJECT_ID}/secrets/HF_TOKEN/versions/latest'
    env: 'HF_TOKEN'

images: ["${_IMAGE}"]
substitutions:
  _IMAGE: 'us-central1-docker.pkg.dev/${PROJECT_ID}/vllm-gemma-3-1b-it-repo/vllm-gemma-3-1b-it'


options:
  dynamicSubstitutions: true
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
