steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  entrypoint: 'bash'
  secretEnv: ['HF_TOKEN']
  args: 
    - -c
    - |
        SECRET_TOKEN="$$HF_TOKEN" docker buildx build --tag=${_IMAGE} --secret id=HF_TOKEN .



availableSecrets:
  secretManager:
  - versionName: 'projects/${PROJECT_ID}/secrets/HF_TOKEN/versions/latest'
  ###- versionName: 'projects/665374072631/secrets/HF_TOKEN/versions/latest'
    env: 'HF_TOKEN'

images: ["${_IMAGE}"]

substitutions:  
  _IMAGE: 'us-central1-docker.pkg.dev/${PROJECT_ID}/vllm-gemma-3-1b-it-repo/vllm-gemma-3-1b-it'
  ###_IMAGE: 'us-central1-docker.pkg.dev/665374072631/vllm-gemma-2-2b-it-repo/vllm-gemma-2-2b-it'
  ##665374072631

options:
  dynamicSubstitutions: true
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
